// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Usuarios API
//
//	API para gestionar usuarios
//	Schemes:
//	  https
//	Host: api.ejemplo.com
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
