// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API para gestionar usuarios",
    "title": "Usuarios API",
    "version": "1.0.0"
  },
  "host": "api.ejemplo.com",
  "basePath": "/v1",
  "paths": {
    "/usuarios": {
      "post": {
        "description": "Crea un nuevo usuario con la información proporcionada",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "usuarios"
        ],
        "summary": "Agrega un nuevo usuario",
        "operationId": "agregarUsuario",
        "parameters": [
          {
            "description": "Usuario a agregar",
            "name": "usuario",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Usuario"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Usuario creado exitosamente",
            "schema": {
              "$ref": "#/definitions/Usuario"
            }
          },
          "400": {
            "description": "Solicitud incorrecta debido a entrada inválida",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/usuarios/{id}": {
      "get": {
        "description": "Retorna un solo usuario",
        "produces": [
          "application/json"
        ],
        "tags": [
          "usuarios"
        ],
        "summary": "Obtiene un usuario por su ID",
        "operationId": "getUsuarioPorId",
        "parameters": [
          {
            "type": "string",
            "description": "ID del usuario a retornar",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Operación exitosa",
            "schema": {
              "$ref": "#/definitions/Usuario"
            }
          },
          "404": {
            "description": "Usuario no encontrado",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "codigo",
        "mensaje"
      ],
      "properties": {
        "codigo": {
          "type": "integer",
          "format": "int32",
          "example": 404
        },
        "mensaje": {
          "type": "string",
          "example": "Usuario no encontrado"
        }
      }
    },
    "Usuario": {
      "type": "object",
      "required": [
        "nombreCompleto",
        "ciudad",
        "estado",
        "numeroTelefonico"
      ],
      "properties": {
        "ciudad": {
          "type": "string",
          "example": "Ciudad de México"
        },
        "estado": {
          "type": "string",
          "example": "CDMX"
        },
        "nombreCompleto": {
          "type": "string",
          "example": "Juan Pérez"
        },
        "numeroTelefonico": {
          "type": "string",
          "example": "+521234567890"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API para gestionar usuarios",
    "title": "Usuarios API",
    "version": "1.0.0"
  },
  "host": "api.ejemplo.com",
  "basePath": "/v1",
  "paths": {
    "/usuarios": {
      "post": {
        "description": "Crea un nuevo usuario con la información proporcionada",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "usuarios"
        ],
        "summary": "Agrega un nuevo usuario",
        "operationId": "agregarUsuario",
        "parameters": [
          {
            "description": "Usuario a agregar",
            "name": "usuario",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Usuario"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Usuario creado exitosamente",
            "schema": {
              "$ref": "#/definitions/Usuario"
            }
          },
          "400": {
            "description": "Solicitud incorrecta debido a entrada inválida",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/usuarios/{id}": {
      "get": {
        "description": "Retorna un solo usuario",
        "produces": [
          "application/json"
        ],
        "tags": [
          "usuarios"
        ],
        "summary": "Obtiene un usuario por su ID",
        "operationId": "getUsuarioPorId",
        "parameters": [
          {
            "type": "string",
            "description": "ID del usuario a retornar",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Operación exitosa",
            "schema": {
              "$ref": "#/definitions/Usuario"
            }
          },
          "404": {
            "description": "Usuario no encontrado",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "codigo",
        "mensaje"
      ],
      "properties": {
        "codigo": {
          "type": "integer",
          "format": "int32",
          "example": 404
        },
        "mensaje": {
          "type": "string",
          "example": "Usuario no encontrado"
        }
      }
    },
    "Usuario": {
      "type": "object",
      "required": [
        "nombreCompleto",
        "ciudad",
        "estado",
        "numeroTelefonico"
      ],
      "properties": {
        "ciudad": {
          "type": "string",
          "example": "Ciudad de México"
        },
        "estado": {
          "type": "string",
          "example": "CDMX"
        },
        "nombreCompleto": {
          "type": "string",
          "example": "Juan Pérez"
        },
        "numeroTelefonico": {
          "type": "string",
          "example": "+521234567890"
        }
      }
    }
  }
}`))
}
