// Code generated by go-swagger; DO NOT EDIT.

package usuarios

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/gleonz/golang-boilerplate/internal/delivery/http/models"
)

// NewAgregarUsuarioParams creates a new AgregarUsuarioParams object
// no default values defined in spec.
func NewAgregarUsuarioParams() AgregarUsuarioParams {

	return AgregarUsuarioParams{}
}

// AgregarUsuarioParams contains all the bound params for the agregar usuario operation
// typically these are obtained from a http.Request
//
// swagger:parameters agregarUsuario
type AgregarUsuarioParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Usuario a agregar
	  Required: true
	  In: body
	*/
	Usuario *models.Usuario
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAgregarUsuarioParams() beforehand.
func (o *AgregarUsuarioParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Usuario
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("usuario", "body", ""))
			} else {
				res = append(res, errors.NewParseError("usuario", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Usuario = &body
			}
		}
	} else {
		res = append(res, errors.Required("usuario", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
