// Code generated by go-swagger; DO NOT EDIT.

package usuarios

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gleonz/golang-boilerplate/internal/delivery/http/models"
)

// GetUsuarioPorIDOKCode is the HTTP code returned for type GetUsuarioPorIDOK
const GetUsuarioPorIDOKCode int = 200

/*
GetUsuarioPorIDOK Operación exitosa

swagger:response getUsuarioPorIdOK
*/
type GetUsuarioPorIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Usuario `json:"body,omitempty"`
}

// NewGetUsuarioPorIDOK creates GetUsuarioPorIDOK with default headers values
func NewGetUsuarioPorIDOK() *GetUsuarioPorIDOK {

	return &GetUsuarioPorIDOK{}
}

// WithPayload adds the payload to the get usuario por Id o k response
func (o *GetUsuarioPorIDOK) WithPayload(payload *models.Usuario) *GetUsuarioPorIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get usuario por Id o k response
func (o *GetUsuarioPorIDOK) SetPayload(payload *models.Usuario) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsuarioPorIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsuarioPorIDNotFoundCode is the HTTP code returned for type GetUsuarioPorIDNotFound
const GetUsuarioPorIDNotFoundCode int = 404

/*
GetUsuarioPorIDNotFound Usuario no encontrado

swagger:response getUsuarioPorIdNotFound
*/
type GetUsuarioPorIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUsuarioPorIDNotFound creates GetUsuarioPorIDNotFound with default headers values
func NewGetUsuarioPorIDNotFound() *GetUsuarioPorIDNotFound {

	return &GetUsuarioPorIDNotFound{}
}

// WithPayload adds the payload to the get usuario por Id not found response
func (o *GetUsuarioPorIDNotFound) WithPayload(payload *models.Error) *GetUsuarioPorIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get usuario por Id not found response
func (o *GetUsuarioPorIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsuarioPorIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
